/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./functions/types.d.ts` (hash: 1762a2161f2981700aab6bea2d0c8165)
interface __BaseEnv_Env {
	PAGE_VIEWS_DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
